<a href="https://colab.research.google.com/github/Harsh-Sharma-10/hello-world/blob/main/WordToVecotor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

In [5]:
print(tf.__version__)

2.19.0


In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
vocab_size = 5000  ### Vocablary size   or text Size

One Hot Encoding

In [22]:
one_hot_rep = [one_hot(i,vocab_size)
for i in sent]
print(one_hot_rep)

[[2566, 3632, 1492, 84], [2566, 3632, 1492, 2599], [2566, 4565, 1492, 4834], [2405, 3626, 4188, 2249, 2943], [2405, 3626, 4188, 2249, 252], [4405, 2566, 4506, 1492, 3903], [3086, 4114, 3866, 2249]]


Word Embedding Representation

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences  # all the sentences is almost same
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [50]:
length = 8      # maximum approximate length of sentances in our text
embedded_words = pad_sequences(one_hot_rep,padding= 'pre',maxlen=length)
print(embedded_words)

[[   0    0    0    0 2566 3632 1492   84]
 [   0    0    0    0 2566 3632 1492 2599]
 [   0    0    0    0 2566 4565 1492 4834]
 [   0    0    0 2405 3626 4188 2249 2943]
 [   0    0    0 2405 3626 4188 2249  252]
 [   0    0    0 4405 2566 4506 1492 3903]
 [   0    0    0    0 3086 4114 3866 2249]]


In [51]:
dim = 10   # dimentions - features on which we represent the word vector

In [52]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [53]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [54]:
print(model.predict(embedded_words))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
[[[ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764
   -0.0122228   0.03362352 -0.04114052 -0.00497079 -0.03469687]
  [ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764
   -0.0122228   0.03362352 -0.04114052 -0.00497079 -0.03469687]
  [ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764
   -0.0122228   0.03362352 -0.04114052 -0.00497079 -0.03469687]
  [ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764
   -0.0122228   0.03362352 -0.04114052 -0.00497079 -0.03469687]
  [-0.00237183 -0.01584886  0.01343126  0.01727441 -0.00129235
    0.00542726  0.0293839   0.01191378 -0.03137411  0.02712486]
  [ 0.04242799  0.0180801  -0.04280105  0.03233022  0.00082985
    0.04869327 -0.02314636 -0.0334325   0.03246489  0.03557216]
  [-0.00083578 -0.04237281  0.01675191 -0.03850322 -0.0192937
   -0.0148256  -0.04635017 -0.01440594  0.00370418 -0.01470852]
  [-0.0160764  -0.02189687  0.04092832  0.00463676 -0.0053517
   -0.01033

In [55]:
embedded_words[0]

array([   0,    0,    0,    0, 2566, 3632, 1492,   84], dtype=int32)

In [56]:
print(model.predict(embedded_words)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764 -0.0122228
   0.03362352 -0.04114052 -0.00497079 -0.03469687]
 [ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764 -0.0122228
   0.03362352 -0.04114052 -0.00497079 -0.03469687]
 [ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764 -0.0122228
   0.03362352 -0.04114052 -0.00497079 -0.03469687]
 [ 0.03888107  0.00830911 -0.04164775  0.02966917  0.03969764 -0.0122228
   0.03362352 -0.04114052 -0.00497079 -0.03469687]
 [-0.00237183 -0.01584886  0.01343126  0.01727441 -0.00129235  0.00542726
   0.0293839   0.01191378 -0.03137411  0.02712486]
 [ 0.04242799  0.0180801  -0.04280105  0.03233022  0.00082985  0.04869327
  -0.02314636 -0.0334325   0.03246489  0.03557216]
 [-0.00083578 -0.04237281  0.01675191 -0.03850322 -0.0192937  -0.0148256
  -0.04635017 -0.01440594  0.00370418 -0.01470852]
 [-0.0160764  -0.02189687  0.04092832  0.00463676 -0.0053517  -0.01033175
  -0.00192233  0.0

Single word i.e at loaction [ i , j ]

In [57]:
print(embedded_words[0][4])

2566


Vector representation of Word at [ i , j ] of embedded_words

In [63]:

print(model.predict(embedded_words)[0][4])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[-0.00237183 -0.01584886  0.01343126  0.01727441 -0.00129235  0.00542726
  0.0293839   0.01191378 -0.03137411  0.02712486]
